# Generated by Django 4.0.5 on 2022-06-29 05:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('alpha_3', models.TextField(db_column='CRY_COD', max_length=3, primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='CRY_NAM', max_length='255')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.EmailField(db_column='USR_EML', max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='User email')),
                ('user_id', models.UUIDField(db_column='USR_COD', default=uuid.uuid4)),
                ('description', models.CharField(blank=True, db_column='USR_NAM', max_length=255)),
                ('date_joined', models.DateField(db_column='ENT_DAT', default=datetime.date.today)),
                ('is_superuser', models.BooleanField(db_column='ADM_FLG', default=False)),
                ('absence_limit', models.IntegerField(db_column='ABS_LMT', default=0)),
                ('is_deleted', models.BooleanField(db_column='T_REC_DLT_FLG', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='T_REC_INS_TST')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='T_REC_UPD_TST')),
                ('deleted_at', models.DateTimeField(db_column='T_REC_SRC_TST', null=True)),
                ('country_code', models.ForeignKey(blank=True, db_column='CRY_COD', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.country')),
            ],
            options={
                'db_table': 'R_USR',
            },
        ),
    ]
