# Generated by Django 4.0.5 on 2022-06-08 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.EmailField(db_column='USR_EML', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, db_column='USR_NAM', max_length=255)),
                ('date_joined', models.DateField(db_column='ENT_DAT', default=datetime.date.today)),
                ('is_superuser', models.BooleanField(db_column='ADM_FLG', default=False)),
                ('absence_limit', models.IntegerField(db_column='ABS_LMT', default=0)),
                ('is_deleted', models.BooleanField(db_column='T_REC_DLT_FLG', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='T_REC_INS_TST')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='T_REC_UPD_TST')),
                ('deleted_at', models.DateTimeField(db_column='T_REC_SRC_TST', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'R_USR',
            },
        ),
    ]
