# Generated by Django 4.0.5 on 2022-06-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('absence_id', models.IntegerField(db_column='ABS_BCK_COD', primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_column='ABS_STR_DAT')),
                ('end_date', models.DateField(db_column='ABS_END_DAT')),
                ('user_comment', models.TextField(db_column='ABS_USR_MSG')),
                ('approval_status_code', models.PositiveSmallIntegerField(choices=[(0, 'Not Approved'), (1, 'In Progress'), (2, 'Approved'), (3, 'Rejected')], db_column='APR_STS_COD', default=0)),
                ('approval_message', models.JSONField(db_column='APR_MSG')),
                ('approval_comment', models.TextField(db_column='APR_CMT')),
                ('is_deleted', models.BooleanField(db_column='T_REC_DLT_FLG', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='T_REC_INS_TST')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='T_REC_UPD_TST')),
                ('deleted_at', models.DateTimeField(db_column='T_REC_SRC_TST')),
            ],
        ),
        migrations.CreateModel(
            name='AbsenceApprovalFlowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status_code', models.PositiveSmallIntegerField(choices=[(0, 'Not Approved'), (1, 'In Progress'), (2, 'Approved'), (3, 'Rejected')], db_column='APR_STS_COD', default=0)),
                ('approval_comment', models.TextField(db_column='APR_CMT')),
            ],
        ),
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_step', models.PositiveSmallIntegerField(db_column='APR_STP')),
                ('approval_user_email', models.EmailField(db_column='APR_USR_EML', max_length=254)),
                ('notification_email_list', models.EmailField(db_column='NTF_EML_LST', max_length=254)),
                ('is_deleted', models.BooleanField(db_column='T_REC_DLT_FLG', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='T_REC_INS_TST')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='T_REC_UPD_TST')),
                ('deleted_at', models.DateTimeField(db_column='T_REC_SRC_TST')),
            ],
        ),
    ]
