# Generated by Django 4.0.5 on 2022-07-04 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('absence_id', models.AutoField(db_column='ABS_BCK_COD', primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_column='ABS_STR_DAT')),
                ('end_date', models.DateField(db_column='ABS_END_DAT')),
                ('user_comment', models.TextField(blank=True, db_column='ABS_USR_MSG')),
                ('approval_status_code', models.PositiveSmallIntegerField(choices=[(0, 'Not Approved'), (1, 'In Progress'), (2, 'Approved'), (3, 'Rejected')], db_column='APR_STS_COD', default=0)),
                ('approval_message', models.TextField(blank=True, db_column='APR_MSG', default='', null=True)),
                ('approval_comment', models.TextField(blank=True, db_column='APR_CMT', default='', null=True)),
                ('is_deleted', models.BooleanField(db_column='T_REC_DLT_FLG', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='T_REC_INS_TST')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='T_REC_UPD_TST')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='T_REC_SRC_TST', null=True)),
            ],
            options={
                'db_table': 'D_ABS_CLD_STS',
            },
        ),
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('absence_type', models.AutoField(db_column='ABS_TYP_COD', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='ABS_TYP_DSC', max_length=255)),
                ('user_selection_flag', models.BooleanField(db_column='USR_SLC_FLG', default=True)),
            ],
            options={
                'db_table': 'R_ABS_TYP',
            },
        ),
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_step', models.PositiveSmallIntegerField(db_column='APR_STP')),
                ('notification_email_list', models.EmailField(blank=True, db_column='NTF_EML_LST', max_length=254, null=True)),
                ('is_deleted', models.BooleanField(db_column='T_REC_DLT_FLG', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='T_REC_INS_TST')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='T_REC_UPD_TST')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='T_REC_SRC_TST', null=True)),
                ('approver', models.ForeignKey(db_column='APR_USR_EML', on_delete=django.db.models.deletion.CASCADE, related_name='approver_flows', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(db_column='USR_EML', on_delete=django.db.models.deletion.CASCADE, related_name='requester_flows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AbsenceApprovalFlowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status_code', models.PositiveSmallIntegerField(choices=[(0, 'Not Approved'), (1, 'In Progress'), (2, 'Approved'), (3, 'Rejected')], db_column='APR_STS_COD', default=0)),
                ('approval_comment', models.TextField(blank=True, db_column='APR_CMT')),
                ('is_deleted', models.BooleanField(db_column='T_REC_DLT_FLG', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='T_REC_INS_TST')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='T_REC_UPD_TST')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='T_REC_SRC_TST', null=True)),
                ('absence', models.ForeignKey(db_column='ABS_BCK_COD', on_delete=django.db.models.deletion.CASCADE, related_name='approval_flow_statuses', to='absences.absence')),
                ('approval_flow', models.ForeignKey(db_column='APR_FLW', on_delete=django.db.models.deletion.CASCADE, to='absences.approvalflow')),
                ('user', models.ForeignKey(db_column='USR_EML', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='absence',
            name='absence_type',
            field=models.ForeignKey(db_column='ABS_TYP_COD', on_delete=django.db.models.deletion.CASCADE, to='absences.absencetype'),
        ),
        migrations.AddField(
            model_name='absence',
            name='user',
            field=models.ForeignKey(db_column='USR_EML', on_delete=django.db.models.deletion.CASCADE, related_name='user_absences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='approvalflow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('requester', 'approval_step'), name='unique_approval_flow'),
        ),
    ]
