# Generated by Django 4.0.5 on 2022-07-05 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='absence_type',
            field=models.ForeignKey(db_column='ABS_TYP_COD', limit_choices_to={'user_selection_flag': True}, on_delete=django.db.models.deletion.CASCADE, to='absences.absencetype'),
        ),
        migrations.AlterField(
            model_name='absencetype',
            name='absence_type',
            field=models.IntegerField(db_column='ABS_TYP_COD', primary_key=True, serialize=False),
        ),
    ]
