# Generated by Django 4.0.5 on 2022-06-08 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('absences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalflow',
            name='user',
            field=models.ForeignKey(db_column='USR_EML', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absenceapprovalflowstatus',
            name='absence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absences.approvalflow'),
        ),
        migrations.AddField(
            model_name='absenceapprovalflowstatus',
            name='user',
            field=models.ForeignKey(db_column='USR_EML', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absence',
            name='user',
            field=models.ForeignKey(db_column='USR_EML', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='approvalflow',
            constraint=models.UniqueConstraint(fields=('user', 'approval_step'), name='unique_approval_flow'),
        ),
    ]
