# Generated by Django 4.0.5 on 2022-06-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='absence_id',
            field=models.AutoField(db_column='ABS_BCK_COD', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='absence',
            name='deleted_at',
            field=models.DateTimeField(db_column='T_REC_SRC_TST', null=True),
        ),
    ]
