# Generated by Django 4.0.5 on 2022-06-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0003_alter_absence_absence_id_alter_absence_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='approval_comment',
            field=models.TextField(blank=True, db_column='APR_CMT'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='approval_message',
            field=models.JSONField(blank=True, db_column='APR_MSG'),
        ),
    ]
