# Generated by Django 4.0.5 on 2022-07-05 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('absences', '0003_alter_absenceapprovalflowstatus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenceapprovalflowstatus',
            name='approval_flow',
            field=models.ForeignKey(db_column='APR_FLW', on_delete=django.db.models.deletion.CASCADE, related_name='approval_flow_statuses', to='absences.approvalflow'),
        ),
        migrations.AlterField(
            model_name='absenceapprovalflowstatus',
            name='user',
            field=models.ForeignKey(db_column='USR_EML', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
