# Generated by Django 4.0.5 on 2022-06-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0004_alter_absence_approval_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='approval_comment',
            field=models.TextField(blank=True, db_column='APR_CMT', null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='approval_message',
            field=models.JSONField(blank=True, db_column='APR_MSG', null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='user_comment',
            field=models.TextField(blank=True, db_column='ABS_USR_MSG'),
        ),
    ]
