# Generated by Django 4.0.5 on 2022-06-08 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('absences', '0005_alter_absence_approval_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='user',
            field=models.ForeignKey(db_column='USR_EML', on_delete=django.db.models.deletion.CASCADE, related_name='user_absences', to=settings.AUTH_USER_MODEL),
        ),
    ]
