# Generated by Django 4.0.5 on 2022-07-08 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('absences', '0005_publicholiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicholiday',
            name='country',
            field=models.ForeignKey(db_column='CRY_COD', on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to=settings.AUTH_USER_MODEL),
        ),
    ]
