# Generated by Django 4.0.5 on 2022-07-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0007_alter_publicholiday_country'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='approvalflow',
            name='unique_approval_flow',
        ),
        migrations.AlterModelTable(
            name='absenceapprovalflowstatus',
            table='D_ABS_APR_FLW',
        ),
        migrations.AlterModelTable(
            name='approvalflow',
            table='R_APR_FLW',
        ),
        migrations.AlterModelTable(
            name='publicholiday',
            table='R_PBL_HLD',
        ),
    ]
