# Generated by Django 4.0.5 on 2022-06-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0007_alter_absence_approval_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='approval_comment',
            field=models.TextField(blank=True, db_column='APR_CMT', default='', null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='approval_message',
            field=models.TextField(blank=True, db_column='APR_MSG', default='', null=True),
        ),
    ]
